import Head from 'next/head'
import { fetchCategories } from '../http'
import { AxiosResponse } from 'axios'
import { ICategory, ICollectionResponse } from '../types'
import { NextPage, GetServerSideProps } from 'next'
import Tab from '../components/Tab'

interface IpropTypes {
  categories: {
    items: ICategory[]
  }
}

const Home: NextPage<IpropTypes> = ({ categories }) => {


  return (
    <>
      <Head>
        <title>Coders Blog Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tab categories={categories.items} />

      <main>
        <h1 className='text-red-500 text-3xl'>Welcome to coders blog</h1>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories()

  return {
    props: {
      categories: {
        items: categories.data
      }
    }
  }



}



export default Home